/**
 * data.js
 * 中国語学習アプリ用データ
 * - 基本単語辞書（日本語→中国語・ピンイン・品詞・例文）
 * - 文法パターン
 * - 漢字→ピンイン変換辞書（大幅拡充・複合語優先）
 */

// ===== 基本単語辞書 =====
const WORD_DICT = [
  // 人・関係
  { ja: "私", zh: "我", pinyin: "wǒ", type: "代名詞", meaning: "私・わたし", example: "我是日本人。(私は日本人です)" },
  { ja: "あなた", zh: "你", pinyin: "nǐ", type: "代名詞", meaning: "あなた", example: "你好！(こんにちは！)" },
  { ja: "彼", zh: "他", pinyin: "tā", type: "代名詞", meaning: "彼・かれ", example: "他是我的朋友。(彼は私の友達です)" },
  { ja: "彼女", zh: "她", pinyin: "tā", type: "代名詞", meaning: "彼女・かのじょ", example: "她很漂亮。(彼女はとても綺麗です)" },
  { ja: "友達", zh: "朋友", pinyin: "péngyou", type: "名詞", meaning: "友達・ともだち", example: "他是我的好朋友。(彼は私の親友です)" },
  { ja: "家族", zh: "家人", pinyin: "jiārén", type: "名詞", meaning: "家族・かぞく", example: "我爱我的家人。(私は家族を愛しています)" },
  { ja: "先生", zh: "老师", pinyin: "lǎoshī", type: "名詞", meaning: "先生・せんせい", example: "老师很好。(先生はとても良い方です)" },

  // 場所
  { ja: "家", zh: "家", pinyin: "jiā", type: "名詞", meaning: "家・いえ", example: "我在家。(私は家にいます)" },
  { ja: "学校", zh: "学校", pinyin: "xuéxiào", type: "名詞", meaning: "学校・がっこう", example: "我去学校。(私は学校に行きます)" },
  { ja: "会社", zh: "公司", pinyin: "gōngsī", type: "名詞", meaning: "会社・かいしゃ", example: "我在公司工作。(私は会社で働いています)" },
  { ja: "カフェ", zh: "咖啡店", pinyin: "kāfēidiàn", type: "名詞", meaning: "カフェ・喫茶店", example: "我们去咖啡店吧。(カフェに行きましょう)" },
  { ja: "レストラン", zh: "餐厅", pinyin: "cāntīng", type: "名詞", meaning: "レストラン・食堂", example: "这家餐厅很好吃。(このレストランはとても美味しい)" },
  { ja: "駅", zh: "车站", pinyin: "chēzhàn", type: "名詞", meaning: "駅・えき", example: "车站在哪里？(駅はどこですか？)" },
  { ja: "公園", zh: "公园", pinyin: "gōngyuán", type: "名詞", meaning: "公園・こうえん", example: "我在公园散步。(私は公園を散歩しています)" },

  // 動詞
  { ja: "行く", zh: "去", pinyin: "qù", type: "動詞", meaning: "行く・いく", example: "我去超市。(私はスーパーに行きます)" },
  { ja: "来る", zh: "来", pinyin: "lái", type: "動詞", meaning: "来る・くる", example: "他来了。(彼が来ました)" },
  { ja: "食べる", zh: "吃", pinyin: "chī", type: "動詞", meaning: "食べる・たべる", example: "我吃饭。(私はご飯を食べます)" },
  { ja: "飲む", zh: "喝", pinyin: "hē", type: "動詞", meaning: "飲む・のむ", example: "我喝咖啡。(私はコーヒーを飲みます)" },
  { ja: "見る", zh: "看", pinyin: "kàn", type: "動詞", meaning: "見る・みる", example: "我看电影。(私は映画を見ます)" },
  { ja: "聞く", zh: "听", pinyin: "tīng", type: "動詞", meaning: "聞く・きく", example: "我听音乐。(私は音楽を聴きます)" },
  { ja: "話す", zh: "说", pinyin: "shuō", type: "動詞", meaning: "話す・はなす", example: "我说中文。(私は中国語を話します)" },
  { ja: "買う", zh: "买", pinyin: "mǎi", type: "動詞", meaning: "買う・かう", example: "我买东西。(私は買い物をします)" },
  { ja: "働く", zh: "工作", pinyin: "gōngzuò", type: "動詞", meaning: "働く・はたらく", example: "我每天工作。(私は毎日働きます)" },
  { ja: "勉強する", zh: "学习", pinyin: "xuéxí", type: "動詞", meaning: "勉強する・べんきょうする", example: "我学习中文。(私は中国語を勉強します)" },
  { ja: "会う", zh: "见面", pinyin: "jiànmiàn", type: "動詞", meaning: "会う・あう", example: "我们明天见面。(私たちは明日会います)" },
  { ja: "帰る", zh: "回去", pinyin: "huíqù", type: "動詞", meaning: "帰る・かえる", example: "我回去了。(私は帰ります)" },
  { ja: "寝る", zh: "睡觉", pinyin: "shuìjiào", type: "動詞", meaning: "寝る・ねる", example: "我去睡觉了。(私は寝ます)" },
  { ja: "起きる", zh: "起床", pinyin: "qǐchuáng", type: "動詞", meaning: "起きる・おきる", example: "我七点起床。(私は7時に起きます)" },

  // 形容詞
  { ja: "美味しい", zh: "好吃", pinyin: "hǎochī", type: "形容詞", meaning: "美味しい・おいしい", example: "这个很好吃！(これはとても美味しい！)" },
  { ja: "楽しい", zh: "开心", pinyin: "kāixīn", type: "形容詞", meaning: "楽しい・たのしい", example: "今天很开心。(今日はとても楽しかった)" },
  { ja: "嬉しい", zh: "高兴", pinyin: "gāoxìng", type: "形容詞", meaning: "嬉しい・うれしい", example: "我很高兴见到你。(あなたに会えて嬉しいです)" },
  { ja: "疲れた", zh: "累", pinyin: "lèi", type: "形容詞", meaning: "疲れた・つかれた", example: "我很累。(私はとても疲れました)" },
  { ja: "忙しい", zh: "忙", pinyin: "máng", type: "形容詞", meaning: "忙しい・いそがしい", example: "我最近很忙。(最近とても忙しいです)" },
  { ja: "綺麗", zh: "漂亮", pinyin: "piàoliang", type: "形容詞", meaning: "綺麗・きれい", example: "这里很漂亮。(ここはとても綺麗です)" },
  { ja: "大きい", zh: "大", pinyin: "dà", type: "形容詞", meaning: "大きい・おおきい", example: "这个很大。(これはとても大きい)" },
  { ja: "小さい", zh: "小", pinyin: "xiǎo", type: "形容詞", meaning: "小さい・ちいさい", example: "这个很小。(これはとても小さい)" },

  // 時間
  { ja: "今日", zh: "今天", pinyin: "jīntiān", type: "名詞", meaning: "今日・きょう", example: "今天天气很好。(今日は天気が良いです)" },
  { ja: "昨日", zh: "昨天", pinyin: "zuótiān", type: "名詞", meaning: "昨日・きのう", example: "昨天我去了公园。(昨日公園に行きました)" },
  { ja: "明日", zh: "明天", pinyin: "míngtiān", type: "名詞", meaning: "明日・あした", example: "明天见！(また明日！)" },
  { ja: "朝", zh: "早上", pinyin: "zǎoshang", type: "名詞", meaning: "朝・あさ", example: "早上好！(おはようございます！)" },
  { ja: "夜", zh: "晚上", pinyin: "wǎnshang", type: "名詞", meaning: "夜・よる", example: "晚上好！(こんばんは！)" },

  // 食べ物・飲み物
  { ja: "コーヒー", zh: "咖啡", pinyin: "kāfēi", type: "名詞", meaning: "コーヒー", example: "我喜欢喝咖啡。(私はコーヒーが好きです)" },
  { ja: "お茶", zh: "茶", pinyin: "chá", type: "名詞", meaning: "お茶・おちゃ", example: "我喝茶。(私はお茶を飲みます)" },
  { ja: "ご飯", zh: "饭", pinyin: "fàn", type: "名詞", meaning: "ご飯・ごはん", example: "我吃饭了。(ご飯を食べました)" },
  { ja: "水", zh: "水", pinyin: "shuǐ", type: "名詞", meaning: "水・みず", example: "我喝水。(私は水を飲みます)" },

  // よく使う表現
  { ja: "ありがとう", zh: "谢谢", pinyin: "xièxie", type: "挨拶", meaning: "ありがとう", example: "谢谢你！(ありがとうございます！)" },
  { ja: "すみません", zh: "对不起", pinyin: "duìbuqǐ", type: "挨拶", meaning: "すみません・ごめんなさい", example: "对不起，我迟到了。(すみません、遅刻しました)" },
  { ja: "こんにちは", zh: "你好", pinyin: "nǐhǎo", type: "挨拶", meaning: "こんにちは", example: "你好！很高兴认识你。(こんにちは！はじめまして)" },
  { ja: "さようなら", zh: "再见", pinyin: "zàijiàn", type: "挨拶", meaning: "さようなら・またね", example: "再见！明天见！(さようなら！また明日！)" },
];

// ===== 文法パターン =====
const GRAMMAR_PATTERNS = [
  {
    pattern: "主語 + 是 + 名詞",
    desc: "「〜は〜です」という基本的な肯定文。英語の be動詞に相当。",
    example: "我是学生。(私は学生です)",
    keywords: ["是"]
  },
  {
    pattern: "主語 + 很 + 形容詞",
    desc: "「〜はとても〜です」。形容詞の前に「很(hěn)」を置く。",
    example: "今天很开心。(今日はとても楽しい)",
    keywords: ["很"]
  },
  {
    pattern: "主語 + 去 + 場所",
    desc: "「〜へ行く」。「去(qù)」の後に目的地を置く。",
    example: "我去学校。(私は学校に行きます)",
    keywords: ["去"]
  },
  {
    pattern: "主語 + 喜欢 + 動詞/名詞",
    desc: "「〜が好きです」。「喜欢(xǐhuān)」で好みを表現。",
    example: "我喜欢喝咖啡。(私はコーヒーを飲むのが好きです)",
    keywords: ["喜欢"]
  },
  {
    pattern: "主語 + 在 + 場所",
    desc: "「〜は〜にいる/ある」。存在・位置を表す。",
    example: "我在家。(私は家にいます)",
    keywords: ["在"]
  },
  {
    pattern: "主語 + 了 (文末)",
    desc: "「〜した」。動作の完了や状況の変化を表す助詞「了(le)」。",
    example: "我吃饭了。(ご飯を食べました)",
    keywords: ["了"]
  },
  {
    pattern: "主語 + 想 + 動詞",
    desc: "「〜したい」。願望・希望を表す助動詞「想(xiǎng)」。",
    example: "我想去中国。(私は中国に行きたいです)",
    keywords: ["想"]
  },
  {
    pattern: "主語 + 和 + 人 + 一起",
    desc: "「〜と一緒に」。「和(hé)」は「〜と」、「一起(yīqǐ)」は「一緒に」。",
    example: "我和朋友一起去。(私は友達と一緒に行きます)",
    keywords: ["和", "一起"]
  },
  {
    pattern: "主語 + 没有 + 動詞",
    desc: "「〜していない」。過去の否定。「没有(méiyǒu)」で否定。",
    example: "我没有去。(私は行きませんでした)",
    keywords: ["没有", "没"]
  },
  {
    pattern: "主語 + 会 + 動詞",
    desc: "「〜できる」。習得した能力・スキルを表す。",
    example: "我会说中文。(私は中国語が話せます)",
    keywords: ["会"]
  },
];

// ===== サンプルエピソード =====
const SAMPLE_EPISODES = [
  "今日は友達とカフェに行きました。美味しいコーヒーを飲みながら、楽しい話をしました。",
  "昨日は会社で忙しかったです。夜は家に帰って、ゆっくり休みました。",
  "今朝は公園を散歩しました。天気がとても良くて、気持ちよかったです。",
  "先生と一緒に中国語を勉強しました。少しずつ上手になっています。",
];

// ===== 漢字→ピンイン変換辞書（複合語優先・大幅拡充版）=====
// 長い単語を先にマッチさせるため、複合語を多数収録
const CHAR_PINYIN = {
  // ===== 4文字以上の複合語 =====
  "对不起": "duìbuqǐ",
  "没关系": "méiguānxi",
  "不客气": "bùkèqi",
  "没问题": "méiwèntí",
  "怎么样": "zěnmeyàng",
  "为什么": "wèishénme",
  "什么时候": "shénmeshíhou",
  "一起来": "yīqǐlái",
  "不知道": "bùzhīdào",
  "告诉我": "gàosùwǒ",
  "咖啡店": "kāfēidiàn",
  "超级市场": "chāojíshìchǎng",

  // ===== 3文字複合語 =====
  "咖啡厅": "kāfēitīng",
  "图书馆": "túshūguǎn",
  "博物馆": "bówùguǎn",
  "超市": "chāoshì",
  "便利店": "biànlìdiàn",
  "地铁站": "dìtiězhàn",
  "公交车": "gōngjiāochē",
  "出租车": "chūzūchē",
  "飞机场": "fēijīchǎng",
  "火车站": "huǒchēzhàn",
  "医院": "yīyuàn",
  "银行": "yínháng",
  "邮局": "yóujú",
  "警察局": "jǐngchájú",
  "大学生": "dàxuéshēng",
  "中学生": "zhōngxuéshēng",
  "小学生": "xiǎoxuéshēng",
  "老师好": "lǎoshīhǎo",
  "同学们": "tóngxuémen",
  "工程师": "gōngchéngshī",
  "服务员": "fúwùyuán",
  "经理": "jīnglǐ",
  "总经理": "zǒngjīnglǐ",
  "公司里": "gōngsīlǐ",
  "手机号": "shǒujīhào",
  "电话号": "diànhuàhào",
  "电子邮件": "diànzǐyóujiàn",
  "互联网": "hùliánwǎng",
  "社交媒体": "shèjiāoméitǐ",
  "天气预报": "tiānqìyùbào",
  "新闻联播": "xīnwénliánbō",
  "电视剧": "diànshìjù",
  "电影院": "diànyǐngyuàn",
  "音乐会": "yīnyuèhuì",
  "运动会": "yùndònghuì",
  "生日快乐": "shēngrìkuàilè",
  "新年快乐": "xīnniánkuàilè",
  "身体健康": "shēntǐjiànkāng",
  "万事如意": "wànshìrúyì",

  // ===== 2文字複合語（頻出・重要）=====
  // 挨拶・基本表現
  "你好": "nǐhǎo",
  "再见": "zàijiàn",
  "谢谢": "xièxie",
  "不好": "bùhǎo",
  "没有": "méiyǒu",
  "一起": "yīqǐ",
  "一下": "yīxià",
  "一点": "yīdiǎn",
  "一样": "yīyàng",
  "一直": "yīzhí",
  "一定": "yīdìng",
  "一共": "yīgòng",
  "一般": "yībān",
  "一边": "yībiān",
  "一会": "yīhuì",
  "一些": "yīxiē",
  "一切": "yīqiē",
  "一次": "yīcì",
  "一种": "yīzhǒng",
  "一块": "yīkuài",
  "一起来": "yīqǐlái",
  "好的": "hǎode",
  "好吃": "hǎochī",
  "好喝": "hǎohē",
  "好看": "hǎokàn",
  "好听": "hǎotīng",
  "好玩": "hǎowán",
  "好用": "hǎoyòng",
  "好像": "hǎoxiàng",
  "好久": "hǎojiǔ",
  "好多": "hǎoduō",
  "好大": "hǎodà",
  "好小": "hǎoxiǎo",
  "好快": "hǎokuài",
  "好慢": "hǎomàn",
  "好热": "hǎorè",
  "好冷": "hǎolěng",
  "好美": "hǎoměi",
  "好棒": "hǎobàng",
  "好厉害": "hǎolìhai",
  "不是": "búshì",
  "不好": "bùhǎo",
  "不行": "bùxíng",
  "不对": "búduì",
  "不用": "búyòng",
  "不要": "búyào",
  "不能": "bùnéng",
  "不会": "búhuì",
  "不知": "bùzhī",
  "不太": "bùtài",
  "不错": "búcuò",
  "不同": "bùtóng",
  "不少": "bùshǎo",
  "不多": "bùduō",
  "不大": "bùdà",
  "不小": "bùxiǎo",
  "不早": "bùzǎo",
  "不晚": "bùwǎn",
  "不快": "bùkuài",
  "不慢": "bùmàn",
  "不热": "bùrè",
  "不冷": "bùlěng",
  "不远": "bùyuǎn",
  "不近": "bùjìn",
  "不贵": "búguì",
  "不便宜": "bùpiányí",
  "不客气": "bùkèqi",
  "不好意思": "bùhǎoyìsi",

  // 人・関係
  "朋友": "péngyou",
  "家人": "jiārén",
  "老师": "lǎoshī",
  "同学": "tóngxué",
  "同事": "tóngshì",
  "父母": "fùmǔ",
  "父亲": "fùqīn",
  "母亲": "mǔqīn",
  "爸爸": "bàba",
  "妈妈": "māma",
  "哥哥": "gēge",
  "姐姐": "jiějie",
  "弟弟": "dìdi",
  "妹妹": "mèimei",
  "爷爷": "yéye",
  "奶奶": "nǎinai",
  "外公": "wàigōng",
  "外婆": "wàipó",
  "丈夫": "zhàngfu",
  "妻子": "qīzi",
  "儿子": "érzi",
  "女儿": "nǚér",
  "孩子": "háizi",
  "男朋友": "nánpéngyou",
  "女朋友": "nǚpéngyou",
  "邻居": "línjū",
  "陌生人": "mòshēngrén",

  // 場所
  "学校": "xuéxiào",
  "公司": "gōngsī",
  "公园": "gōngyuán",
  "车站": "chēzhàn",
  "地铁": "dìtiě",
  "机场": "jīchǎng",
  "火车": "huǒchē",
  "餐厅": "cāntīng",
  "咖啡": "kāfēi",
  "超市": "chāoshì",
  "商店": "shāngdiàn",
  "商场": "shāngchǎng",
  "书店": "shūdiàn",
  "药店": "yàodiàn",
  "理发店": "lǐfàdiàn",
  "洗手间": "xǐshǒujiān",
  "卫生间": "wèishēngjiān",
  "厕所": "cèsuǒ",
  "宾馆": "bīnguǎn",
  "酒店": "jiǔdiàn",
  "旅馆": "lǚguǎn",
  "教室": "jiàoshì",
  "办公室": "bàngōngshì",
  "会议室": "huìyìshì",
  "图书馆": "túshūguǎn",
  "操场": "cāochǎng",
  "体育馆": "tǐyùguǎn",
  "游泳池": "yóuyǒngchí",
  "停车场": "tíngchēchǎng",

  // 動詞（複合）
  "工作": "gōngzuò",
  "学习": "xuéxí",
  "见面": "jiànmiàn",
  "回去": "huíqù",
  "回来": "huílái",
  "回家": "huíjiā",
  "睡觉": "shuìjiào",
  "起床": "qǐchuáng",
  "吃饭": "chīfàn",
  "喝水": "hēshuǐ",
  "喝茶": "hēchá",
  "看书": "kànshū",
  "看电视": "kàndiànshì",
  "看电影": "kàndiànyǐng",
  "听音乐": "tīngyīnyuè",
  "说话": "shuōhuà",
  "打电话": "dǎdiànhuà",
  "发短信": "fāduǎnxìn",
  "上网": "shàngwǎng",
  "玩游戏": "wányóuxì",
  "做作业": "zuòzuòyè",
  "做饭": "zuòfàn",
  "洗澡": "xǐzǎo",
  "刷牙": "shuāyá",
  "洗脸": "xǐliǎn",
  "穿衣服": "chuānyīfu",
  "散步": "sànbù",
  "跑步": "pǎobù",
  "游泳": "yóuyǒng",
  "打球": "dǎqiú",
  "踢足球": "tīzúqiú",
  "打篮球": "dǎlánqiú",
  "打网球": "dǎwǎngqiú",
  "骑自行车": "qízìxíngchē",
  "开车": "kāichē",
  "坐车": "zuòchē",
  "坐地铁": "zuòdìtiě",
  "坐公交": "zuògōngjiāo",
  "坐飞机": "zuòfēijī",
  "坐火车": "zuòhuǒchē",
  "买东西": "mǎidōngxi",
  "买票": "mǎipiào",
  "付钱": "fùqián",
  "找钱": "zhǎoqián",
  "换钱": "huànqián",
  "借钱": "jièqián",
  "还钱": "huánqián",
  "存钱": "cúnqián",
  "取钱": "qǔqián",
  "花钱": "huāqián",
  "省钱": "shěngqián",
  "赚钱": "zhuànqián",
  "喜欢": "xǐhuān",
  "讨厌": "tǎoyàn",
  "害怕": "hàipà",
  "担心": "dānxīn",
  "高兴": "gāoxìng",
  "开心": "kāixīn",
  "伤心": "shāngxīn",
  "生气": "shēngqì",
  "着急": "zháojí",
  "紧张": "jǐnzhāng",
  "放松": "fàngsōng",
  "休息": "xiūxi",
  "睡眠": "shuìmián",
  "锻炼": "duànliàn",
  "旅游": "lǚyóu",
  "旅行": "lǚxíng",
  "出发": "chūfā",
  "到达": "dàodá",
  "出门": "chūmén",
  "进来": "jìnlái",
  "出去": "chūqù",
  "进去": "jìnqù",
  "上来": "shànglái",
  "下来": "xiàlái",
  "上去": "shàngqù",
  "下去": "xiàqù",
  "过来": "guòlái",
  "过去": "guòqù",
  "起来": "qǐlái",
  "出来": "chūlái",
  "认识": "rènshi",
  "了解": "liǎojiě",
  "理解": "lǐjiě",
  "明白": "míngbai",
  "知道": "zhīdào",
  "告诉": "gàosu",
  "问题": "wèntí",
  "回答": "huídá",
  "解释": "jiěshì",
  "解决": "jiějué",
  "帮助": "bāngzhù",
  "支持": "zhīchí",
  "鼓励": "gǔlì",
  "批评": "pīpíng",
  "表扬": "biǎoyáng",
  "感谢": "gǎnxiè",
  "道歉": "dàoqiàn",
  "原谅": "yuánliàng",
  "拒绝": "jùjué",
  "同意": "tóngyì",
  "反对": "fǎnduì",
  "建议": "jiànyì",
  "决定": "juédìng",
  "计划": "jìhuà",
  "准备": "zhǔnbèi",
  "开始": "kāishǐ",
  "结束": "jiéshù",
  "完成": "wánchéng",
  "继续": "jìxù",
  "停止": "tíngzhǐ",
  "改变": "gǎibiàn",
  "发展": "fāzhǎn",
  "进步": "jìnbù",
  "提高": "tígāo",
  "增加": "zēngjiā",
  "减少": "jiǎnshǎo",
  "注意": "zhùyì",
  "小心": "xiǎoxīn",
  "当心": "dāngxīn",
  "保护": "bǎohù",
  "保持": "bǎochí",
  "保证": "bǎozhèng",
  "保留": "bǎoliú",
  "保存": "bǎocún",
  "使用": "shǐyòng",
  "利用": "lìyòng",
  "需要": "xūyào",
  "应该": "yīnggāi",
  "必须": "bìxū",
  "可以": "kěyǐ",
  "能够": "nénggòu",
  "允许": "yǔnxǔ",
  "禁止": "jìnzhǐ",
  "要求": "yāoqiú",
  "希望": "xīwàng",
  "期待": "qīdài",
  "相信": "xiāngxìn",
  "怀疑": "huáiyí",
  "觉得": "juéde",
  "认为": "rènwéi",
  "感觉": "gǎnjué",
  "感受": "gǎnshòu",
  "感情": "gǎnqíng",
  "感动": "gǎndòng",
  "感谢": "gǎnxiè",
  "感激": "gǎnjī",
  "感兴趣": "gǎnxìngqù",
  "有意思": "yǒuyìsi",
  "没意思": "méiyìsi",
  "有趣": "yǒuqù",
  "无聊": "wúliáo",
  "有用": "yǒuyòng",
  "没用": "méiyòng",
  "重要": "zhòngyào",
  "不重要": "bùzhòngyào",
  "方便": "fāngbiàn",
  "不方便": "bùfāngbiàn",
  "容易": "róngyì",
  "困难": "kùnnán",
  "简单": "jiǎndān",
  "复杂": "fùzá",
  "清楚": "qīngchǔ",
  "模糊": "móhu",
  "正确": "zhèngquè",
  "错误": "cuòwù",
  "成功": "chénggōng",
  "失败": "shībài",
  "努力": "nǔlì",
  "认真": "rènzhēn",
  "仔细": "zǐxì",
  "马虎": "mǎhu",
  "聪明": "cōngming",
  "笨": "bèn",
  "勤快": "qínkuài",
  "懒惰": "lǎnduò",
  "诚实": "chéngshí",
  "说谎": "shuōhuǎng",
  "礼貌": "lǐmào",
  "粗鲁": "cūlǔ",
  "热情": "rèqíng",
  "冷漠": "lěngmò",
  "友好": "yǒuhǎo",
  "友善": "yǒushàn",
  "善良": "shànliáng",
  "坏": "huài",
  "可爱": "kě'ài",
  "帅气": "shuàiqi",
  "漂亮": "piàoliang",
  "美丽": "měilì",
  "英俊": "yīngjùn",
  "丑": "chǒu",
  "胖": "pàng",
  "瘦": "shòu",
  "高": "gāo",
  "矮": "ǎi",
  "强壮": "qiángzhuàng",
  "虚弱": "xūruò",
  "健康": "jiànkāng",
  "生病": "shēngbìng",
  "发烧": "fāshāo",
  "头疼": "tóuténg",
  "肚子疼": "dùziténg",
  "感冒": "gǎnmào",
  "咳嗽": "késou",
  "过敏": "guòmǐn",
  "受伤": "shòushāng",
  "手术": "shǒushù",
  "药": "yào",
  "医生": "yīshēng",
  "护士": "hùshi",
  "病人": "bìngrén",

  // 食べ物・飲み物
  "咖啡": "kāfēi",
  "奶茶": "nǎichá",
  "果汁": "guǒzhī",
  "啤酒": "píjiǔ",
  "白酒": "báijiǔ",
  "红酒": "hóngjiǔ",
  "矿泉水": "kuàngquánshuǐ",
  "可乐": "kělè",
  "雪碧": "xuěbì",
  "牛奶": "niúnǎi",
  "豆浆": "dòujiāng",
  "米饭": "mǐfàn",
  "面条": "miàntiáo",
  "饺子": "jiǎozi",
  "包子": "bāozi",
  "馒头": "mántou",
  "面包": "miànbāo",
  "蛋糕": "dàngāo",
  "饼干": "bǐnggān",
  "糖果": "tángguǒ",
  "巧克力": "qiǎokèlì",
  "冰淇淋": "bīngqílín",
  "水果": "shuǐguǒ",
  "苹果": "píngguǒ",
  "香蕉": "xiāngjiāo",
  "橙子": "chéngzi",
  "葡萄": "pútao",
  "草莓": "cǎoméi",
  "西瓜": "xīguā",
  "蔬菜": "shūcài",
  "白菜": "báicài",
  "土豆": "tǔdòu",
  "西红柿": "xīhóngshì",
  "黄瓜": "huángguā",
  "豆腐": "dòufu",
  "鸡肉": "jīròu",
  "猪肉": "zhūròu",
  "牛肉": "niúròu",
  "羊肉": "yángròu",
  "鱼肉": "yúròu",
  "虾": "xiā",
  "螃蟹": "pángxiè",
  "鸡蛋": "jīdàn",
  "炒饭": "chǎofàn",
  "炒菜": "chǎocài",
  "火锅": "huǒguō",
  "烤肉": "kǎoròu",
  "寿司": "shòusī",
  "拉面": "lāmiàn",
  "汉堡": "hànbǎo",
  "披萨": "pīsà",
  "沙拉": "shālā",
  "汤": "tāng",
  "粥": "zhōu",

  // 時間
  "今天": "jīntiān",
  "昨天": "zuótiān",
  "明天": "míngtiān",
  "后天": "hòutiān",
  "前天": "qiántiān",
  "早上": "zǎoshang",
  "上午": "shàngwǔ",
  "中午": "zhōngwǔ",
  "下午": "xiàwǔ",
  "晚上": "wǎnshang",
  "深夜": "shēnyè",
  "凌晨": "língchén",
  "今年": "jīnnián",
  "去年": "qùnián",
  "明年": "míngnián",
  "上个月": "shànggeyuè",
  "这个月": "zhègeyuè",
  "下个月": "xiàgeyuè",
  "上周": "shàngzhōu",
  "这周": "zhèzhōu",
  "下周": "xiàzhōu",
  "星期一": "xīngqīyī",
  "星期二": "xīngqīèr",
  "星期三": "xīngqīsān",
  "星期四": "xīngqīsì",
  "星期五": "xīngqīwǔ",
  "星期六": "xīngqīliù",
  "星期天": "xīngqītiān",
  "星期日": "xīngqīrì",
  "周一": "zhōuyī",
  "周二": "zhōuèr",
  "周三": "zhōusān",
  "周四": "zhōusì",
  "周五": "zhōuwǔ",
  "周六": "zhōuliù",
  "周日": "zhōurì",
  "元旦": "yuándàn",
  "春节": "chūnjié",
  "清明节": "qīngmíngjié",
  "劳动节": "láodòngjié",
  "国庆节": "guóqìngjié",
  "中秋节": "zhōngqiūjié",
  "圣诞节": "shèngdànjié",
  "情人节": "qíngrénjiē",
  "母亲节": "mǔqīnjié",
  "父亲节": "fùqīnjié",
  "生日": "shēngrì",
  "纪念日": "jìniànrì",
  "假期": "jiàqī",
  "节假日": "jiéjiàrì",
  "工作日": "gōngzuòrì",
  "休息日": "xiūxirì",
  "时间": "shíjiān",
  "时候": "shíhou",
  "现在": "xiànzài",
  "以前": "yǐqián",
  "以后": "yǐhòu",
  "将来": "jiānglái",
  "过去": "guòqù",
  "最近": "zuìjìn",
  "马上": "mǎshàng",
  "立刻": "lìkè",
  "已经": "yǐjīng",
  "还没": "háiméi",
  "刚才": "gāngcái",
  "刚刚": "gānggāng",
  "经常": "jīngcháng",
  "常常": "chángcháng",
  "有时": "yǒushí",
  "有时候": "yǒushíhou",
  "偶尔": "ǒu'ěr",
  "从来": "cónglái",
  "总是": "zǒngshì",
  "一直": "yīzhí",
  "终于": "zhōngyú",
  "突然": "tūrán",
  "忽然": "hūrán",

  // 数量・程度
  "一点儿": "yīdiǎnr",
  "一些": "yīxiē",
  "很多": "hěnduō",
  "很少": "hěnshǎo",
  "不少": "bùshǎo",
  "不多": "bùduō",
  "太多": "tàiduō",
  "太少": "tàishǎo",
  "差不多": "chàbuduō",
  "大概": "dàgài",
  "大约": "dàyuē",
  "左右": "zuǒyòu",
  "以上": "yǐshàng",
  "以下": "yǐxià",
  "以内": "yǐnèi",
  "以外": "yǐwài",
  "最多": "zuìduō",
  "最少": "zuìshǎo",
  "最大": "zuìdà",
  "最小": "zuìxiǎo",
  "最好": "zuìhǎo",
  "最坏": "zuìhuài",
  "最高": "zuìgāo",
  "最低": "zuìdī",
  "最快": "zuìkuài",
  "最慢": "zuìmàn",
  "最近": "zuìjìn",
  "最远": "zuìyuǎn",
  "最贵": "zuìguì",
  "最便宜": "zuìpiányí",
  "非常": "fēicháng",
  "特别": "tèbié",
  "相当": "xiāngdāng",
  "比较": "bǐjiào",
  "稍微": "shāowēi",
  "有点": "yǒudiǎn",
  "有点儿": "yǒudiǎnr",
  "挺": "tǐng",
  "蛮": "mán",
  "超": "chāo",
  "极了": "jíle",
  "死了": "sǐle",

  // 方向・位置
  "上面": "shàngmiàn",
  "下面": "xiàmiàn",
  "前面": "qiánmiàn",
  "后面": "hòumiàn",
  "左边": "zuǒbiān",
  "右边": "yòubiān",
  "里面": "lǐmiàn",
  "外面": "wàimiàn",
  "中间": "zhōngjiān",
  "旁边": "pángbiān",
  "附近": "fùjìn",
  "对面": "duìmiàn",
  "周围": "zhōuwéi",
  "东边": "dōngbiān",
  "西边": "xībiān",
  "南边": "nánbiān",
  "北边": "běibiān",
  "东方": "dōngfāng",
  "西方": "xīfāng",
  "南方": "nánfāng",
  "北方": "běifāng",
  "这里": "zhèlǐ",
  "那里": "nàlǐ",
  "哪里": "nǎlǐ",
  "这边": "zhèbiān",
  "那边": "nàbiān",
  "哪边": "nǎbiān",
  "这儿": "zhèr",
  "那儿": "nàr",
  "哪儿": "nǎr",

  // 天気・自然
  "天气": "tiānqì",
  "晴天": "qíngtiān",
  "阴天": "yīntiān",
  "下雨": "xiàyǔ",
  "下雪": "xiàxuě",
  "刮风": "guāfēng",
  "打雷": "dǎléi",
  "闪电": "shǎndiàn",
  "台风": "táifēng",
  "地震": "dìzhèn",
  "洪水": "hóngshuǐ",
  "干旱": "gānhàn",
  "温度": "wēndù",
  "气温": "qìwēn",
  "湿度": "shīdù",
  "太阳": "tàiyáng",
  "月亮": "yuèliang",
  "星星": "xīngxing",
  "云": "yún",
  "雨": "yǔ",
  "雪": "xuě",
  "风": "fēng",
  "雾": "wù",
  "彩虹": "cǎihóng",
  "山": "shān",
  "河": "hé",
  "湖": "hú",
  "海": "hǎi",
  "森林": "sēnlín",
  "草地": "cǎodì",
  "沙漠": "shāmò",
  "岛屿": "dǎoyǔ",

  // 交通・移動
  "交通": "jiāotōng",
  "道路": "dàolù",
  "高速公路": "gāosùgōnglù",
  "红绿灯": "hónglǜdēng",
  "斑马线": "bānmǎxiàn",
  "人行道": "rénxíngdào",
  "自行车": "zìxíngchē",
  "摩托车": "mótuōchē",
  "汽车": "qìchē",
  "公共汽车": "gōnggòngqìchē",
  "出租车": "chūzūchē",
  "地铁": "dìtiě",
  "火车": "huǒchē",
  "高铁": "gāotiě",
  "飞机": "fēijī",
  "轮船": "lúnchuán",
  "船": "chuán",
  "票": "piào",
  "车票": "chēpiào",
  "机票": "jīpiào",
  "护照": "hùzhào",
  "签证": "qiānzhèng",
  "行李": "xíngli",
  "背包": "bēibāo",
  "地图": "dìtú",
  "导航": "dǎoháng",
  "路线": "lùxiàn",
  "方向": "fāngxiàng",
  "距离": "jùlí",
  "速度": "sùdù",

  // 買い物・お金
  "钱": "qián",
  "价格": "jiàgé",
  "价钱": "jiàqian",
  "便宜": "piányí",
  "贵": "guì",
  "打折": "dǎzhé",
  "优惠": "yōuhuì",
  "免费": "miǎnfèi",
  "收费": "shōufèi",
  "付款": "fùkuǎn",
  "找零": "zhǎolíng",
  "发票": "fāpiào",
  "收据": "shōujù",
  "信用卡": "xìnyòngkǎ",
  "现金": "xiànjīn",
  "人民币": "rénmínbì",
  "美元": "měiyuán",
  "日元": "rìyuán",
  "欧元": "ōuyuán",
  "汇率": "huìlǜ",
  "银行卡": "yínhángkǎ",
  "ATM": "ATM",
  "网购": "wǎnggòu",
  "快递": "kuàidì",
  "外卖": "wàimài",
  "订单": "dìngdān",
  "退款": "tuìkuǎn",
  "退货": "tuìhuò",
  "换货": "huànhuò",

  // 学習・仕事
  "汉语": "hànyǔ",
  "中文": "zhōngwén",
  "英语": "yīngyǔ",
  "日语": "rìyǔ",
  "韩语": "hányǔ",
  "法语": "fǎyǔ",
  "德语": "déyǔ",
  "西班牙语": "xībānyáyǔ",
  "语言": "yǔyán",
  "文字": "wénzì",
  "汉字": "hànzì",
  "拼音": "pīnyīn",
  "声调": "shēngdiào",
  "词语": "cíyǔ",
  "句子": "jùzi",
  "语法": "yǔfǎ",
  "发音": "fāyīn",
  "口语": "kǒuyǔ",
  "书写": "shūxiě",
  "阅读": "yuèdú",
  "听力": "tīnglì",
  "翻译": "fānyì",
  "词典": "cídiǎn",
  "教材": "jiàocái",
  "课本": "kèběn",
  "作业": "zuòyè",
  "考试": "kǎoshì",
  "成绩": "chéngjì",
  "分数": "fēnshù",
  "及格": "jígé",
  "不及格": "bùjígé",
  "优秀": "yōuxiù",
  "良好": "liánghǎo",
  "合格": "hégé",
  "毕业": "bìyè",
  "入学": "rùxué",
  "上课": "shàngkè",
  "下课": "xiàkè",
  "课程": "kèchéng",
  "专业": "zhuānyè",
  "研究": "yánjiū",
  "论文": "lùnwén",
  "报告": "bàogào",
  "会议": "huìyì",
  "讨论": "tǎolùn",
  "演讲": "yǎnjiǎng",
  "介绍": "jièshào",
  "说明": "shuōmíng",
  "解释": "jiěshì",
  "分析": "fēnxī",
  "总结": "zǒngjié",
  "评价": "píngjià",
  "反馈": "fǎnkuì",
  "建议": "jiànyì",
  "意见": "yìjiàn",
  "想法": "xiǎngfǎ",
  "观点": "guāndiǎn",
  "态度": "tàidu",
  "立场": "lìchǎng",
  "目标": "mùbiāo",
  "计划": "jìhuà",
  "方案": "fāng'àn",
  "策略": "cèlüè",
  "方法": "fāngfǎ",
  "技术": "jìshù",
  "技能": "jìnéng",
  "经验": "jīngyàn",
  "能力": "nénglì",
  "水平": "shuǐpíng",
  "程度": "chéngdù",
  "效果": "xiàoguǒ",
  "结果": "jiéguǒ",
  "原因": "yuányīn",
  "理由": "lǐyóu",
  "目的": "mùdì",
  "意义": "yìyì",
  "价值": "jiàzhí",
  "作用": "zuòyòng",
  "影响": "yǐngxiǎng",
  "关系": "guānxi",
  "联系": "liánxì",
  "合作": "hézuò",
  "竞争": "jìngzhēng",
  "比赛": "bǐsài",
  "游戏": "yóuxì",
  "运动": "yùndòng",
  "体育": "tǐyù",
  "音乐": "yīnyuè",
  "美术": "měishù",
  "艺术": "yìshù",
  "文化": "wénhuà",
  "历史": "lìshǐ",
  "地理": "dìlǐ",
  "科学": "kēxué",
  "数学": "shùxué",
  "物理": "wùlǐ",
  "化学": "huàxué",
  "生物": "shēngwù",
  "政治": "zhèngzhì",
  "经济": "jīngjì",
  "社会": "shèhuì",
  "法律": "fǎlǜ",
  "医学": "yīxué",
  "哲学": "zhéxué",
  "心理学": "xīnlǐxué",
  "教育": "jiàoyù",
  "新闻": "xīnwén",
  "媒体": "méitǐ",
  "网络": "wǎngluò",
  "电脑": "diànnǎo",
  "手机": "shǒujī",
  "平板": "píngbǎn",
  "软件": "ruǎnjiàn",
  "应用": "yìngyòng",
  "程序": "chéngxù",
  "数据": "shùjù",
  "信息": "xìnxī",
  "通信": "tōngxìn",
  "电话": "diànhuà",
  "短信": "duǎnxìn",
  "邮件": "yóujiàn",
  "视频": "shìpín",
  "照片": "zhàopiàn",
  "图片": "túpiàn",
  "文件": "wénjiàn",
  "文档": "wéndàng",
  "密码": "mìmǎ",
  "账号": "zhànghào",
  "注册": "zhùcè",
  "登录": "dēnglù",
  "退出": "tuìchū",
  "下载": "xiàzài",
  "上传": "shàngchuán",
  "搜索": "sōusuǒ",
  "分享": "fēnxiǎng",
  "点赞": "diǎnzàn",
  "评论": "pínglùn",
  "关注": "guānzhù",
  "粉丝": "fěnsī",

  // 代名詞
  "我们": "wǒmen",
  "你们": "nǐmen",
  "他们": "tāmen",
  "她们": "tāmen",
  "它们": "tāmen",
  "大家": "dàjiā",
  "自己": "zìjǐ",
  "别人": "biérén",
  "对方": "duìfāng",
  "双方": "shuāngfāng",
  "这个": "zhège",
  "那个": "nàge",
  "哪个": "nǎge",
  "这些": "zhèxiē",
  "那些": "nàxiē",
  "哪些": "nǎxiē",
  "什么": "shénme",
  "怎么": "zěnme",
  "为什么": "wèishénme",
  "怎样": "zěnyàng",
  "多少": "duōshao",
  "几个": "jǐge",
  "谁": "shéi",
  "哪": "nǎ",

  // 接続詞・副詞
  "因为": "yīnwèi",
  "所以": "suǒyǐ",
  "但是": "dànshì",
  "虽然": "suīrán",
  "如果": "rúguǒ",
  "只要": "zhǐyào",
  "只有": "zhǐyǒu",
  "除非": "chúfēi",
  "除了": "chúle",
  "不但": "búdàn",
  "而且": "érqiě",
  "不仅": "bùjǐn",
  "还是": "háishi",
  "或者": "huòzhě",
  "要么": "yàome",
  "既然": "jìrán",
  "尽管": "jǐnguǎn",
  "即使": "jíshǐ",
  "就算": "jiùsuàn",
  "不管": "bùguǎn",
  "无论": "wúlùn",
  "不论": "bùlùn",
  "只是": "zhǐshì",
  "不过": "búguò",
  "然而": "rán'ér",
  "另外": "lìngwài",
  "此外": "cǐwài",
  "总之": "zǒngzhī",
  "总的来说": "zǒngdeláishuō",
  "一方面": "yīfāngmiàn",
  "另一方面": "lìngyīfāngmiàn",
  "首先": "shǒuxiān",
  "其次": "qícì",
  "最后": "zuìhòu",
  "然后": "ránhòu",
  "接着": "jiēzhe",
  "同时": "tóngshí",
  "一边": "yībiān",
  "一方面": "yīfāngmiàn",
  "相反": "xiāngfǎn",
  "相同": "xiāngtóng",
  "相似": "xiāngsì",
  "相关": "xiāngguān",
  "互相": "hùxiāng",
  "彼此": "bǐcǐ",
  "各自": "gèzì",
  "分别": "fēnbié",
  "共同": "gòngtóng",
  "一起": "yīqǐ",
  "一同": "yītóng",
  "一块儿": "yīkuàir",
  "单独": "dāndú",
  "独自": "dúzì",
  "亲自": "qīnzì",
  "特意": "tèyì",
  "故意": "gùyì",
  "偶然": "ǒurán",
  "必然": "bìrán",
  "当然": "dāngrán",
  "果然": "guǒrán",
  "居然": "jūrán",
  "竟然": "jìngrán",
  "幸好": "xìnghǎo",
  "幸亏": "xìngkuī",
  "可惜": "kěxī",
  "遗憾": "yíhàn",
  "没想到": "méixiǎngdào",
  "没关系": "méiguānxi",
  "没问题": "méiwèntí",
  "没办法": "méibànfǎ",
  "没必要": "méibìyào",
  "有必要": "yǒubìyào",
  "有可能": "yǒukěnéng",
  "没可能": "méikěnéng",
  "不可能": "bùkěnéng",
  "有意思": "yǒuyìsi",
  "没意思": "méiyìsi",
  "有意义": "yǒuyìyì",
  "没意义": "méiyìyì",

  // ===== 1文字（単独で使われる場合のフォールバック）=====
  // 代名詞
  "我": "wǒ", "你": "nǐ", "他": "tā", "她": "tā", "它": "tā",
  "们": "men",
  // 動詞
  "是": "shì", "有": "yǒu", "在": "zài", "去": "qù", "来": "lái",
  "吃": "chī", "喝": "hē", "看": "kàn", "听": "tīng", "说": "shuō",
  "买": "mǎi", "做": "zuò", "走": "zǒu", "跑": "pǎo",
  "坐": "zuò", "站": "zhàn", "睡": "shuì", "起": "qǐ",
  "工": "gōng", "作": "zuò", "学": "xué", "习": "xí",
  "见": "jiàn", "面": "miàn", "回": "huí", "爱": "ài",
  "想": "xiǎng", "会": "huì", "能": "néng", "可": "kě",
  "知": "zhī", "道": "dào", "认": "rèn", "识": "shí",
  "喜": "xǐ", "欢": "huān", "帮": "bāng", "助": "zhù",
  "开": "kāi", "心": "xīn", "高": "gāo", "兴": "xìng",
  "谢": "xiè", "对": "duì", "不": "bù",
  "用": "yòng", "给": "gěi", "从": "cóng", "到": "dào",
  "比": "bǐ", "像": "xiàng", "跟": "gēn", "把": "bǎ",
  "被": "bèi", "让": "ràng", "叫": "jiào",
  "写": "xiě", "读": "dú", "问": "wèn", "答": "dá",
  "找": "zhǎo", "拿": "ná", "放": "fàng", "带": "dài",
  "送": "sòng", "接": "jiē", "等": "děng", "请": "qǐng",
  "借": "jiè", "还": "huán", "换": "huàn", "卖": "mài",
  "付": "fù", "收": "shōu", "存": "cún", "取": "qǔ",
  "花": "huā", "省": "shěng", "赚": "zhuàn",
  "打": "dǎ", "踢": "tī", "骑": "qí", "游": "yóu",
  "唱": "chàng", "跳": "tiào", "画": "huà", "弹": "tán",
  "玩": "wán", "笑": "xiào", "哭": "kū", "叫": "jiào",
  "睡": "shuì", "醒": "xǐng", "洗": "xǐ", "穿": "chuān",
  "脱": "tuō", "戴": "dài", "摘": "zhāi",
  "吃": "chī", "喝": "hē", "尝": "cháng", "闻": "wén",
  "摸": "mō", "抱": "bào", "握": "wò", "推": "tuī",
  "拉": "lā", "举": "jǔ", "扔": "rēng", "接": "jiē",
  "开": "kāi", "关": "guān", "锁": "suǒ", "开": "kāi",
  "修": "xiū", "建": "jiàn", "造": "zào", "破": "pò",
  "切": "qiē", "剪": "jiǎn", "折": "zhé", "撕": "sī",
  "烧": "shāo", "煮": "zhǔ", "炒": "chǎo", "炸": "zhá",
  "烤": "kǎo", "蒸": "zhēng", "煎": "jiān",
  "种": "zhòng", "摘": "zhāi", "浇": "jiāo",
  "养": "yǎng", "喂": "wèi", "抓": "zhuā",
  "飞": "fēi", "跳": "tiào", "爬": "pá", "游": "yóu",
  "转": "zhuǎn", "停": "tíng", "动": "dòng",
  "增": "zēng", "减": "jiǎn", "加": "jiā", "乘": "chéng",
  "除": "chú", "等": "děng", "约": "yuē",
  "选": "xuǎn", "投": "tóu", "票": "piào",
  "赢": "yíng", "输": "shū", "平": "píng",
  "生": "shēng", "死": "sǐ", "活": "huó",
  "长": "zhǎng", "大": "dà", "小": "xiǎo",
  "变": "biàn", "成": "chéng", "为": "wéi",
  "让": "ràng", "使": "shǐ", "叫": "jiào",
  "把": "bǎ", "将": "jiāng",
  // 名詞
  "人": "rén", "家": "jiā", "校": "xiào",
  "公": "gōng", "司": "sī", "园": "yuán", "店": "diàn",
  "车": "chē", "路": "lù", "门": "mén",
  "朋": "péng", "友": "yǒu", "老": "lǎo", "师": "shī",
  "父": "fù", "母": "mǔ", "子": "zǐ", "女": "nǚ",
  "书": "shū", "报": "bào", "纸": "zhǐ", "笔": "bǐ",
  "水": "shuǐ", "茶": "chá", "饭": "fàn", "菜": "cài",
  "肉": "ròu", "鱼": "yú", "蛋": "dàn",
  "咖": "kā", "啡": "fēi", "餐": "cān", "厅": "tīng",
  "钱": "qián", "年": "nián",
  "月": "yuè", "日": "rì", "天": "tiān", "号": "hào",
  "点": "diǎn", "分": "fēn",
  "里": "lǐ", "外": "wài", "中": "zhōng", "间": "jiān",
  "北": "běi", "南": "nán", "东": "dōng", "西": "xī",
  "这": "zhè", "那": "nà", "哪": "nǎ",
  "头": "tóu", "手": "shǒu", "脚": "jiǎo", "眼": "yǎn",
  "耳": "ěr", "鼻": "bí", "嘴": "zuǐ", "脸": "liǎn",
  "身": "shēn", "体": "tǐ", "心": "xīn", "脑": "nǎo",
  "背": "bèi", "腿": "tuǐ", "臂": "bì", "指": "zhǐ",
  "衣": "yī", "服": "fú", "裤": "kù", "裙": "qún",
  "鞋": "xié", "袜": "wà", "帽": "mào", "包": "bāo",
  "桌": "zhuō", "椅": "yǐ", "床": "chuáng", "柜": "guì",
  "窗": "chuāng", "墙": "qiáng", "地": "dì", "楼": "lóu",
  "房": "fáng", "室": "shì", "厨": "chú", "卫": "wèi",
  "灯": "dēng", "电": "diàn", "气": "qì", "水": "shuǐ",
  "锅": "guō", "碗": "wǎn", "盘": "pán", "杯": "bēi",
  "筷": "kuài", "勺": "sháo", "刀": "dāo", "叉": "chā",
  "花": "huā", "草": "cǎo", "树": "shù", "叶": "yè",
  "果": "guǒ", "根": "gēn", "枝": "zhī",
  "猫": "māo", "狗": "gǒu", "鸟": "niǎo", "鱼": "yú",
  "马": "mǎ", "牛": "niú", "羊": "yáng", "猪": "zhū",
  "鸡": "jī", "鸭": "yā", "兔": "tù", "熊": "xióng",
  "虎": "hǔ", "狮": "shī", "象": "xiàng", "猴": "hóu",
  "蛇": "shé", "龙": "lóng",
  "国": "guó", "省": "shěng", "市": "shì", "区": "qū",
  "县": "xiàn", "镇": "zhèn", "村": "cūn",
  "中国": "zhōngguó", "日本": "rìběn", "美国": "měiguó",
  "英国": "yīngguó", "法国": "fǎguó", "德国": "déguó",
  "韩国": "hánguó", "俄国": "éguó",
  "北京": "běijīng", "上海": "shànghǎi", "广州": "guǎngzhōu",
  "深圳": "shēnzhèn", "成都": "chéngdū", "西安": "xī'ān",
  "东京": "dōngjīng", "大阪": "dàbǎn", "京都": "jīngdū",
  // 形容詞・副詞
  "好": "hǎo", "大": "dà", "小": "xiǎo", "多": "duō",
  "少": "shǎo", "新": "xīn", "旧": "jiù", "快": "kuài",
  "慢": "màn", "热": "rè", "冷": "lěng", "美": "měi",
  "漂": "piào", "亮": "liàng", "忙": "máng", "累": "lèi",
  "很": "hěn", "太": "tài", "真": "zhēn", "非": "fēi",
  "常": "cháng", "也": "yě", "都": "dōu", "还": "hái",
  "已": "yǐ", "经": "jīng", "就": "jiù", "才": "cái",
  "再": "zài", "又": "yòu", "还": "hái", "更": "gèng",
  "最": "zuì", "很": "hěn", "挺": "tǐng", "蛮": "mán",
  "超": "chāo", "极": "jí", "特": "tè", "别": "bié",
  "相": "xiāng", "当": "dāng", "比": "bǐ", "较": "jiào",
  "稍": "shāo", "微": "wēi", "有": "yǒu", "点": "diǎn",
  "远": "yuǎn", "近": "jìn", "高": "gāo", "低": "dī",
  "长": "cháng", "短": "duǎn", "宽": "kuān", "窄": "zhǎi",
  "厚": "hòu", "薄": "báo", "重": "zhòng", "轻": "qīng",
  "硬": "yìng", "软": "ruǎn", "干": "gān", "湿": "shī",
  "净": "jìng", "脏": "zāng", "整": "zhěng", "乱": "luàn",
  "空": "kōng", "满": "mǎn", "够": "gòu", "缺": "quē",
  "对": "duì", "错": "cuò", "真": "zhēn", "假": "jiǎ",
  "正": "zhèng", "反": "fǎn", "顺": "shùn", "逆": "nì",
  "早": "zǎo", "晚": "wǎn", "前": "qián", "后": "hòu",
  "上": "shàng", "下": "xià", "左": "zuǒ", "右": "yòu",
  "内": "nèi", "外": "wài", "中": "zhōng",
  // 助詞・接続詞
  "的": "de", "了": "le", "吗": "ma", "呢": "ne",
  "啊": "a", "吧": "ba", "和": "hé", "或": "huò",
  "但": "dàn", "因": "yīn", "为": "wèi", "所": "suǒ",
  "以": "yǐ", "如": "rú", "虽": "suī",
  "然": "rán", "着": "zhe", "过": "guò", "得": "de",
  "地": "de", "被": "bèi", "把": "bǎ", "将": "jiāng",
  "向": "xiàng", "往": "wǎng", "朝": "cháo",
  "于": "yú", "与": "yǔ", "及": "jí",
  "而": "ér", "且": "qiě", "则": "zé", "即": "jí",
  "若": "ruò", "当": "dāng", "等": "děng",
  "只": "zhǐ", "仅": "jǐn", "才": "cái", "就": "jiù",
  "都": "dōu", "也": "yě", "还": "hái", "又": "yòu",
  "再": "zài", "更": "gèng", "最": "zuì",
  "没": "méi", "不": "bù", "别": "bié", "莫": "mò",
  "请": "qǐng", "让": "ràng", "叫": "jiào",
  // 数字
  "一": "yī", "二": "èr", "三": "sān", "四": "sì",
  "五": "wǔ", "六": "liù", "七": "qī", "八": "bā",
  "九": "jiǔ", "十": "shí", "百": "bǎi", "千": "qiān",
  "万": "wàn", "零": "líng", "两": "liǎng",
  "第": "dì", "次": "cì", "个": "gè", "些": "xiē",
  "种": "zhǒng", "类": "lèi", "件": "jiàn", "本": "běn",
  "张": "zhāng", "块": "kuài", "条": "tiáo", "根": "gēn",
  "支": "zhī", "把": "bǎ", "双": "shuāng", "对": "duì",
  "套": "tào", "组": "zǔ", "批": "pī", "堆": "duī",
  "群": "qún", "队": "duì", "班": "bān", "组": "zǔ",
  "层": "céng", "排": "pái", "列": "liè", "行": "háng",
  "页": "yè", "段": "duàn", "句": "jù", "字": "zì",
  "词": "cí", "章": "zhāng", "节": "jié", "篇": "piān",
  "部": "bù", "册": "cè", "卷": "juǎn",
  "克": "kè", "千克": "qiānkè", "斤": "jīn", "两": "liǎng",
  "升": "shēng", "毫升": "háoshēng", "杯": "bēi", "碗": "wǎn",
  "米": "mǐ", "千米": "qiānmǐ", "厘米": "límǐ", "毫米": "háomǐ",
  "平方米": "píngfāngmǐ", "公里": "gōnglǐ",
  "度": "dù", "摄氏度": "shèshìdù",
  "元": "yuán", "角": "jiǎo", "分": "fēn",
  "岁": "suì", "年": "nián", "月": "yuè", "天": "tiān",
  "小时": "xiǎoshí", "分钟": "fēnzhōng", "秒": "miǎo",
};

/**
 * 中国語テキストにピンインを付与してHTMLを生成する（改良版）
 * - 複合語を優先的にマッチ（長い順）
 * - 声調記号付きピンインを正確に表示
 * @param {string} text - 中国語テキスト
 * @returns {string} - ピンイン付きHTML文字列
 */
function addPinyinToText(text) {
  if (!text) return '';

  // 長さ順（降順）にソートしたキー一覧を作成
  const sortedKeys = Object.keys(CHAR_PINYIN).sort((a, b) => b.length - a.length);

  let html = '';
  let i = 0;

  while (i < text.length) {
    let matched = false;

    // 長い順にマッチを試みる
    for (const word of sortedKeys) {
      if (text.startsWith(word, i)) {
        const pinyin = CHAR_PINYIN[word];
        if (word.length === 1) {
          // 1文字
          html += `<span class="pinyin-block"><span class="pinyin-ruby">${pinyin}</span><span class="pinyin-char">${word}</span></span>`;
        } else {
          // 複合語：各文字を個別ブロックで表示し、ピンインを分割して対応させる
          const pinyinParts = splitPinyin(pinyin, word.length);
          for (let j = 0; j < word.length; j++) {
            html += `<span class="pinyin-block"><span class="pinyin-ruby">${pinyinParts[j] || ''}</span><span class="pinyin-char">${word[j]}</span></span>`;
          }
        }
        i += word.length;
        matched = true;
        break;
      }
    }

    if (!matched) {
      const char = text[i];
      if (/[\u4e00-\u9fff\u3400-\u4dbf]/.test(char)) {
        // 辞書にない漢字
        html += `<span class="pinyin-block"><span class="pinyin-ruby">?</span><span class="pinyin-char">${char}</span></span>`;
      } else {
        // 漢字以外（句読点・スペース・英数字等）
        const escaped = char.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;');
        html += `<span class="pinyin-char pinyin-punct">${escaped}</span>`;
      }
      i++;
    }
  }

  return html;
}

/**
 * ピンイン文字列を指定文字数に分割する
 * 例: "wǒmen" → ["wǒ", "men"]（2文字の場合）
 * スペース区切りがあればそれを使い、なければ音節境界で分割
 * @param {string} pinyin - ピンイン文字列
 * @param {number} charCount - 漢字の文字数
 * @returns {string[]} - 分割されたピンイン配列
 */
function splitPinyin(pinyin, charCount) {
  if (charCount === 1) return [pinyin];

  // スペース区切りがある場合
  if (pinyin.includes(' ')) {
    const parts = pinyin.split(' ');
    if (parts.length === charCount) return parts;
  }

  // 声調記号付き母音で音節を分割
  const syllablePattern = /[bpmfdtnlgkhjqxzcsryw]?[h]?[iuüaeiouāáǎàēéěèīíǐìōóǒòūúǔùǖǘǚǜ]+[ng]?[r]?/gi;
  const syllables = pinyin.match(syllablePattern) || [];

  if (syllables.length === charCount) return syllables;

  // 分割できない場合は全体を最初の文字に割り当て
  const result = new Array(charCount).fill('');
  result[0] = pinyin;
  return result;
}
